---
:LastProcessedNewsItem: 0
:LastProcessingTime: !ruby/object:DateTime 2013-07-12 17:26:26.339502000 +04:00
:URL: http://192.168.20.240/api/index.php
:KEY: 90af5076-827d-4784-f5b1-012fc77f6d77
:SECRET: NDIxOGViMGEtYjQ1MC03ZDU0LTY1OTItMGE3MzE1NWQwMzQwZjE1OTM3ODktZjhlYi0zMzc0LTQ1YTktNTUzMDExMjIzYThi
...
